apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: warmup-deployment
  name: warmup-deployment
  namespace: ckad-warmup
spec:
  replicas: 3
  selector:
    matchLabels:
      app: warmup-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: warmup-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
