apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: broken-deployment
  name: broken-deployment
  namespace: ckad-troubleshooting
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: brokendeployment
status:
  loadBalancer: {}
