apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: debug-pod
  name: debug-pod
  namespace: ckad-troubleshooting
spec:
  containers:
  - image: nginx
    name: debug-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
