apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: pod3
  name: pod3
  namespace: ckad-network-policys
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: pod3
status:
  loadBalancer: {}
